services:
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file: ../../.env
  backend:
    container_name: backend
    build:
      context: ./django
    image: backend
    volumes:
      - ../django/:/app
      - ../frontend/:/frontend
    ports:
      - "8000:8000"
    env_file: ../../.env
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: ./nginx
    image: frontend
    volumes:
      - ../frontend/:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend