services:
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file: ../../.env
    networks:
      - app-network


  backend:
    container_name: backend
    build:
      context: ./django
    image: backend
    volumes:
      - ../django/:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file: ../../.env
    depends_on:
      - db
  
  
  frontend:
    container_name: frontend
    build:
      context: ./nginx
    image: frontend
    volumes:
      - ../frontend/:/usr/share/nginx/html
      - ../django/media/:/app/media
      - ../django/staticfiles/:/app/staticfiles
    ports:
      - "8042:80"
    networks:
      - app-network
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge