# Generated by Django 5.0.6 on 2024-12-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_match_players_match_player1_match_player2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='points_at_stake',
            new_name='score',
        ),
    ]
