# Generated by Django 5.0.6 on 2024-12-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_match_tournamentmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournamentMatch',
        ),
    ]
