# Generated by Django 5.0.6 on 2024-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_remove_match_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
