# Generated by Django 5.0.6 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
