# Generated by Django 5.0.6 on 2024-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_match_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='match',
            name='points_at_stake',
            field=models.IntegerField(default=0),
        ),
    ]
