# Generated by Django 5.0.6 on 2024-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_is_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
