# Generated by Django 5.0.6 on 2024-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_game',
            field=models.CharField(choices=[('pong', 'Pong'), ('tictactoe', 'Tic-tac-toe')], default='pong', max_length=20),
        ),
    ]
