# Generated by Django 5.0.6 on 2025-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_selected_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.JSONField(default=dict),
        ),
    ]
