# Generated by Django 5.0.6 on 2025-03-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_score_user_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
