# Generated by Django 5.0.6 on 2025-03-16 11:38

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_friendship_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, message="Le nom d'utilisateur doit contenir au moins 3 caractères."), django.core.validators.RegexValidator(message="Le nom d'utilisateur ne peut contenir que des lettres, des chiffres, des tirets et des underscores.", regex='^[a-zA-Z0-9_-]+$'), account.models.validate_reserved_username]),
        ),
    ]
