# Generated by Django 5.0.6 on 2025-03-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
    ]
