# Generated by Django 5.0.6 on 2025-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
