# Generated by Django 5.0.6 on 2024-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intra_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
