# Generated by Django 5.0.6 on 2024-09-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_tournament_rounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='matches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_in_tournament', to='tournament.tournamentmatch'),
        ),
    ]
