# Generated by Django 5.0.6 on 2024-09-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_round_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='matches',
        ),
    ]
