# Generated by Django 5.0.6 on 2024-12-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_remove_tournamentmatch_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdemerde',
            name='tournamentMatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentmatch'),
        ),
    ]
