# Generated by Django 5.0.6 on 2024-12-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_alter_matchdemerde_tournamentmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdemerde',
            name='tournamentMatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='tournament.tournamentmatch'),
        ),
    ]
