# Generated by Django 5.0.6 on 2024-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_tournamentmatch_match_alter_tournamentmatch_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='selected_game',
            field=models.CharField(choices=[('pong', 'Pong'), ('tictactoe', 'Tic-tac-toe')], default='pong', max_length=20),
        ),
    ]
