# Generated by Django 5.0.6 on 2025-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner_place',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
