# Generated by Django 5.0.6 on 2024-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='participants',
            new_name='Players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_players',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
