# Generated by Django 5.0.6 on 2024-08-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_participants_tournament_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='Players',
            new_name='players',
        ),
    ]
