# Generated by Django 5.0.6 on 2024-09-02 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournamentmatch_player2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='matches',
            field=models.ManyToManyField(related_name='rounds', to='tournament.tournamentmatch'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.ManyToManyField(related_name='tournaments', to='tournament.round'),
        ),
    ]
