# Generated by Django 5.0.6 on 2024-09-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournamentmatch_round_alter_round_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='matches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_in_tournament', to='tournament.tournamentmatch'),
        ),
    ]
