# Generated by Django 5.0.6 on 2024-09-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournament.tournamentmatch'),
        ),
    ]
