# Generated by Django 5.0.6 on 2024-12-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_alter_match_player1_alter_match_player2_and_more'),
        ('tournament', '0019_remove_round_tournament_tournament_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='Round',
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_match', to='pong.match'),
        ),
    ]
