# Generated by Django 5.0.6 on 2024-12-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_matchdemerde_alter_tournament_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='match',
        ),
        migrations.AddField(
            model_name='matchdemerde',
            name='tournamentMatch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='tournament.tournamentmatch'),
        ),
    ]
