# Generated by Django 5.0.6 on 2024-12-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_alter_matchdemerde_tournamentmatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchDeMerde',
        ),
    ]
